name: Blockscout

on: push

jobs:
  credo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.10.3'
      - run: mix local.hex --force
      - run: mix credo