name: Blockscout

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.10.3'
      # - run: ./bin/install_chrome_headless.sh
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - name: Cache mix.exs
        uses: actions/cache@v2
        with:
          path: ~/
          key: |
            v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.lock" }}
            v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.exs" }}
            v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          restore-keys: v8-mix-compile-
      - run: mix deps.get
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: |
            v7-npm-install-{{ .Branch }}-{{ checksum "apps/block_scout_web/assets/package-lock.json" }}
            'v7-npm-install-{{ .Branch }}'
            v7-npm-install
          restore-keys: v7-npm-install-
      - run: npm install
        working-directory: apps/explorer
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: apps/explorer/node_modules
          key: >-
            v3-npm-install-{{ .Branch }}-{{ checksum
            "apps/explorer/package-lock.json" }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: apps/explorer/node_modules
          key: 'v3-npm-install-{{ .Branch }}'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: apps/explorer/node_modules
          key: v3-npm-install
      - run: npm install
        working-directory: apps/block_scout_web/assets
      - run: npm rebuild node-sass
        working-directory: apps/block_scout_web/assets
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: apps/block_scout_web/assets/node_modules
          key: >-
            v7-npm-install-{{ .Branch }}-{{ checksum
            "apps/block_scout_web/assets/package-lock.json" }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: apps/block_scout_web/assets/node_modules
          key: 'v7-npm-install-{{ .Branch }}'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: apps/block_scout_web/assets/node_modules
          key: v7-npm-install
      - run: mix compile
      - run: make
        working-directory: "deps/libsecp256k1"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
             deps
             _build
          key: >-
            v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum
            "ELIXIR_VERSION.lock" }}-{{ checksum "mix.lock" }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
             deps
             _build
          key: >-
            v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum
            "ELIXIR_VERSION.lock" }}-{{ checksum "mix.exs" }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
             deps
             _build
          key: >-
            v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum
            "ELIXIR_VERSION.lock" }}
      - name: Build assets
        run: node node_modules/webpack/bin/webpack.js --mode development
        working-directory: "apps/block_scout_web/assets"
      # - name: Upload files
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: blockscout
      #     path: |
      #        .circleci
      #        .credo.exs
      #        .dialyzerignore
      #        .formatter.exs
      #        .git
      #        .gitignore
      #        ELIXIR_VERSION.lock
      #        Gemfile
      #        Gemfile.lock
      #        OTP_VERSION.lock
      #        _build
      #        apps
      #        bin
      #        config
      #        deps
      #        doc
      #        mix.exs
      #        mix.lock
      #        appspec.yml
      #        rel
      - name: mix credo
        run: |
          mix local.hex --force
          mix credo