name: Blockscout

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.10.3'
      # - run: ./bin/install_chrome_headless.sh
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: npm install
        working-directory: apps/explorer
      - run: npm install
        working-directory: apps/block_scout_web/assets
      - run: mix compile
      - run: make
        working-directory: "deps/libsecp256k1"
      - name: Build assets
        run: node node_modules/webpack/bin/webpack.js --mode development
        working-directory: "apps/block_scout_web/assets"
  credo:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: mix local.hex --force
      - run: mix credo